### ISSUE TITLE
Bypassing schema results in collection without hooks

### ISSUE THREAD

**Issue by Floriferous** [Herteby/denormalize#15]
I'm using this package through grapher, and when I define a cache with `bypassSchema: true`, this package throws the following error:

```sh
TypeError: Cannot read property 'insert' of undefined
W20190315-09:56:31.177(1)? (STDERR)     at ns.Collection.Mongo.Collection.cache (packages/herteby:denormalize/cache.js:112:28)
W20190315-09:56:31.177(1)? (STDERR)     at Linker._initDenormalization (packages/cultofcoders:grapher/lib/links/linker.js:444:33)
W20190315-09:56:31.177(1)? (STDERR)     at new Linker (packages/cultofcoders:grapher/lib/links/linker.js:28:14)
W20190315-09:56:31.177(1)? (STDERR)     at _.each (packages/cultofcoders:grapher/lib/links/extension.js:23:28)
W20190315-09:56:31.178(1)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:147:22)
W20190315-09:56:31.178(1)? (STDERR)     at ns.Collection.addLinks (packages/cultofcoders:grapher/lib/links/extension.js:14:11)
W20190315-09:56:31.178(1)? (STDERR)     at links.js (imports/core/api/loans/links.js:14:1)
W20190315-09:56:31.178(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190315-09:56:31.178(1)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190315-09:56:31.178(1)? (STDERR)     at Module.moduleLink [as link] (/Users/Florian/.meteor/packages/modules/.0.13.0.1aurolz.v3oz++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190315-09:56:31.178(1)? (STDERR)     at links.js (imports/core/api/links.js:1:1)
W20190315-09:56:31.178(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190315-09:56:31.179(1)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190315-09:56:31.179(1)? (STDERR)     at Module.moduleLink [as link] (/Users/Florian/.meteor/packages/modules/.0.13.0.1aurolz.v3oz++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190315-09:56:31.179(1)? (STDERR)     at api-server.js (imports/core/api/api-server.js:1:1)
W20190315-09:56:31.196(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
```

From what I can see, `this.parentCollection.after` is undefined, meaning that when you get `this._collection`, that collection doesn't have hooks on it.

It might just be a question of putting the packages in the right order in `.meteor/packages`, but I've already tried putting `matb33:collection-hooks` before grapher, and before this package, without success.

cc: @theodorDiaconu

**Comment by Floriferous** [comment]
I just ended up not using bypassSchema, bummer!
